feat(workflow): Add typescript linter on the precommit git hooks

diff --git a/devutils/git-hooks/pre-commit b/devutils/git-hooks/pre-commit
--- a/devutils/git-hooks/pre-commit
+++ b/devutils/git-hooks/pre-commit
@@ -10,11 +10,23 @@ source "$(dirname "${BASH_SOURCE[0]}")/../lib/bash/bazel.bash"
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/bash/logging.bash"
 source "$(dirname "${BASH_SOURCE[0]}")/../lib/bash/prompt.bash"
 
+
 # Rules checking Go code validity
 PreCommit::GoChecks () {
     [ -z "$GOPATH" ] && Log::Failure "please install golang on workstation (\$GOPATH missing)"
 
     # TODO(funkysayu) add go precommits
+}
+
+
+# Rules checking Typescript code validity
+PreCommit::TypeScriptChecks () {
+    local filepath="$1"
+
+    which npm > /dev/null || Log::Failure "npm binary not found. Aborting..."
+    which tslint > /dev/null || Prompt::YesNoPrompt "Please install tslint: 'sudo npm install -g tslint typescript'"
+
+    tslint -c "devutils/tslint.json" $filepath || Log::Failure "Invalid typescript file. Please fix."
 }
 
 
@@ -51,10 +63,13 @@ main () {
     # Per languages rules
     git diff --name-only --staged HEAD | while read filepath
     do
-        case "$filepath" in
-            *.go) PreCommit::GoChecks $filepath  || exit 1 ;;
-            *BUILD) PreCommit::BuildChecks $filepath || exit 1 ;;
-        esac
+        if [ -e "$filepath" ]; then
+            case "$filepath" in
+                *.go) PreCommit::GoChecks $filepath || exit 1 ;;
+                *.ts) PreCommit::TypeScriptChecks $filepath || exit 1;;
+                *BUILD) PreCommit::BuildChecks $filepath || exit 1 ;;
+            esac
+        fi
     done
 }
 
